
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftDIVMULADD ASSIGN COLON DIV ID INT INT_TYPE LET LPAREN MUL RPAREN SEMICOLON SUBprogram : statementsstatement : expressionstatements : statement\n| statements statementstatement : emptyexpression : variableexpression : bin_opsvariable : INTbin_ops    : expression ADD expression\n| expression SUB expression\n| expression MUL expression\n| expression DIV expressiontype : INT_TYPEstatement : LET ID COLON type ASSIGN expressionempty : optional_semicolon : SEMICOLON\n| empty'
    
_lr_action_items = {'LET':([0,2,3,4,5,7,8,9,10,16,17,18,19,24,],[6,6,-3,-2,-5,-6,-7,-8,-4,-9,-10,-11,-12,-14,]),'INT':([0,2,3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,23,24,],[9,9,-3,-2,-5,-6,-7,-8,-4,9,9,9,9,-9,-10,-11,-12,9,-14,]),'$end':([0,1,2,3,4,5,7,8,9,10,16,17,18,19,24,],[-15,0,-1,-3,-2,-5,-6,-7,-8,-4,-9,-10,-11,-12,-14,]),'ADD':([4,7,8,9,16,17,18,19,24,],[11,-6,-7,-8,-9,-10,-11,-12,11,]),'SUB':([4,7,8,9,16,17,18,19,24,],[12,-6,-7,-8,-9,-10,-11,-12,12,]),'MUL':([4,7,8,9,16,17,18,19,24,],[13,-6,-7,-8,13,13,-11,-12,13,]),'DIV':([4,7,8,9,16,17,18,19,24,],[14,-6,-7,-8,14,14,-11,-12,14,]),'ID':([6,],[15,]),'COLON':([15,],[20,]),'INT_TYPE':([20,],[22,]),'ASSIGN':([21,22,],[23,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,10,]),'expression':([0,2,11,12,13,14,23,],[4,4,16,17,18,19,24,]),'empty':([0,2,],[5,5,]),'variable':([0,2,11,12,13,14,23,],[7,7,7,7,7,7,7,]),'bin_ops':([0,2,11,12,13,14,23,],[8,8,8,8,8,8,8,]),'type':([20,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parse.py',30),
  ('statement -> expression','statement',1,'p_statement','parse.py',34),
  ('statements -> statement','statements',1,'p_statements','parse.py',38),
  ('statements -> statements statement','statements',2,'p_statements','parse.py',39),
  ('statement -> empty','statement',1,'p_statement_empty','parse.py',46),
  ('expression -> variable','expression',1,'p_expression_variable','parse.py',52),
  ('expression -> bin_ops','expression',1,'p_expression_binops','parse.py',56),
  ('variable -> INT','variable',1,'p_variable','parse.py',62),
  ('bin_ops -> expression ADD expression','bin_ops',3,'p_binops_expr','parse.py',70),
  ('bin_ops -> expression SUB expression','bin_ops',3,'p_binops_expr','parse.py',71),
  ('bin_ops -> expression MUL expression','bin_ops',3,'p_binops_expr','parse.py',72),
  ('bin_ops -> expression DIV expression','bin_ops',3,'p_binops_expr','parse.py',73),
  ('type -> INT_TYPE','type',1,'p_type','parse.py',79),
  ('statement -> LET ID COLON type ASSIGN expression','statement',6,'p_assign_stmt','parse.py',85),
  ('empty -> <empty>','empty',0,'p_empty','parse.py',91),
  ('optional_semicolon -> SEMICOLON','optional_semicolon',1,'p_optional_semicolon','parse.py',95),
  ('optional_semicolon -> empty','optional_semicolon',1,'p_optional_semicolon','parse.py',96),
]
